config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #get 'users/new'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'

  get '/services', to: 'static_pages#services'

  get '/gallery', to: 'static_pages#gallery'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

# add users model to the route
  resources :users
  resources :properties, only: [:create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates(:user_id, presence: true)
  validates(:content, presence: true, length: { maximum: 140 })
end

app/models/user.rb
class User < ApplicationRecord
  # initialize users with different properties and terminate listing with the user exit
  has_many :properties, dependent: :destroy
  # show the required fields by calling the validate method
  before_save { mail.downcase! }
  validates(:fname, presence: true, length: { maximum: 50 })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:mail, presence: true, length: { maximum: 244 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false })
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

# defines proto-feed for post updates
  def feed

  end
class << self
  # Returns the hash digest of the given string.
  def digest(string)
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST
:
                                                BCrypt::Engine.cost
BCrypt::Password.create(string, cost: cost)
  end
# Returns a random token.
  def new_token
  SecureRandom.urlsafe_base64
  end
end
# Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
  update_attribute(:remember_digest, User.digest(remember_token))
  end
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # session storage
  include SessionsHelper
  #def hello
  #  render text: 'hello world!'
  #end
  #confirmed a login user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "please login"
      redirect_to login_url
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @property = current_user.properties.build(property_params)
    if @property.save
      flash[:success] = 'Property Created!'
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

private
  def property_params
    params.require(:property).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.find_by(mail: params[:session][:mail].downcase)
  if user && user.authenticate(params[:session][:password])
    log_in user
    params[:session][:remember_me] == '1' ? remember(user) :
    forget(user)
    redirect_back_or user
    #login users and redirect_to profile pages
  else
    # display an error message
    flash.now[:danger] = 'invalid email/password combination'
    render 'new'
  end
end

def destroy
  log_out if logged_in?
  redirect_to root_url
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @property = current_user.properties.build if logged_in?
  end

  def services
  end

  def gallery
  end

  def contact
  end

  def signup
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @properties = @user.properties.paginate(page: params[:page])
    #debugger
  end
  def new
    @user = User.new
  end
  #handles login error on the user path
  def create
    @user = User.new(user_params)
    if @user.save
      #handles successful reg
      log_in @user
      flash[:success] = 'Welcome to NextLegend Real Estate Company'
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:fname, :mail, :password, :password_confirmation)
  end

  #before_filters
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
  flash[:danger] = "Please log in."
  redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end
  #logout current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  #returns the current logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
    @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      raise
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  #returns true if the user is logged-in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #return gravatar for a given user
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.mail.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.fname, class: 'gravatar')

  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>CopyRight NextLegend 2017</small>
  <nav>
    <ul>
      <li><%= link_to 'Home', '#' %></li>
      <li><%= link_to 'Services', '#' %></li>
      <li><%= link_to 'Gallery', '#' %></li>
      <li><%= link_to 'Contact', '#' %></li>
      <li><%= link_to 'Signup', '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class=" container">
    <nav>
      <%= link_to 'NextLegend', 'home', id: 'logo' %>
      <ul class="nav navbar-nav navbar-right head">
        <li><%= link_to 'Home', 'home' %></li>
        <li><%= link_to 'Services', 'services' %></li>
        <li><%= link_to 'Gallery', 'gallery' %></li>
        <li><%= link_to 'Contact', 'contact' %></li>
        <li><%= link_to 'Signup', 'signup' %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", "#" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", "#" %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %> 
      </ul>
    </nav>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/ html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | NextLegend Real Estate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
      <%= message %>
      </div>
      <% end %>
      <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/properties/_property.html.erb
<li id="property-<%= property.id %>" >
  <%= link_to gravatar_for(property.user, size: 50), property.user %>
  <span class="user"><%= link_to property.user.fname, property.user %>
  </span>
  <span class="content"><%= property.content %></span>
  <span class="timestamp">
  Posted <%= time_ago_in_words(property.created_at) %> ago.
</span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_property_form.html.erb
<%= form_for(@property) do |f| %> 
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "Compose new property lissting..." %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.fname %></h1>
<span><%= link_to 'view my profile', current_user %></span>
<span><%= pluralize(current_user.properties.count, "property") %></span>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | NextLegend Real Estate</title>
  </head>
  <body>
    <p>this is my contact page for NextLegend</p>
  </body>
</html>

app/views/static_pages/gallery.html.erb
<% provide(:title, 'Gallery') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> <%= yield(:title) %> | NextLegend Real Estate</title>
  </head>
  <body>
    <p>this is my gallery page for NextLegend</p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | NextLegend Real Estate</title>
  </head>
  <body>
    <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/property_form' %>
        </section>
      </aside>
     </div>
     <% else %>
    <p>
      this is my home page for NextLegend
    </p>
    <% end %>
  </body>
</html>

app/views/static_pages/services.html.erb
<% provide(:title, 'Services') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | NextLegend Real Estate</title>
  </head>
  <body>
    <p>this is my service page for NextLegend</p>
  </body>
</html>

app/views/static_pages/signup.html.erb
<% provide(:title, 'Signup') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | NextLegend Real Estate</title>
  </head>
  <body>
    <p>this is my signup page for NextLegend</p>
  </body>
</html>

app/views/users/new.html.erb
<%= provide(:title, 'Signup') %>
<h1>sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :fname %>
    <%= f.label :email %>
    <%= f.email_field :mail  %>
    <%= f.label :password %>
    <%= f.password_field :password  %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation  %>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.fname) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.fname %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.properties.any? %>
    <!--h3>Properties(<%= @user.properties.count %>)</h3-->
    <ol class="microposts">
      <%= render @properties %>
    </ol>
    <%= will_paginate @properties %>
    <% end %>
  </div>
</div>